Repository yearn/yearn-exporter, pull requests merged in 2022-10, with the labels that each got.

#410 fix(partners): add another loop for vaults and force POOL_SIZE=1
  scripts/exporters/partners.py
Labels: safe to test

#409 fix: guard usage of chainlink feeds per network
  yearn/apy/common.py
  yearn/prices/uniswap/uniswap.py
Labels: p1, testing

#411 Feat/revenues weekly
  Makefile
  scripts/revenues.py
  yearn/treasury/treasury.py
Labels: p1

#401 feat: Add Spool Yearn partnership program configuration
  yearn/partners/partners.py
Labels: b2b, safe to test

#421 Added Phuture's vault controllers to partners.py
  yearn/partners/partners.py
Labels: safe to test
