Repository yearn/yearn-exporter, pull requests merged in 2022-04, with the labels that each got.

#282 [EXP-82-282] added qidao's dai and ftm vaults
  yearn/partners/partners.py
Labels: do not merge, b2b, blocked

#289 [EXP-89-289] feat: Gnosis chain
  Makefile
  entrypoint.sh
  scripts/historical_exporter.py
  scripts/historical_sms_exporter.py
  scripts/historical_treasury_exporter.py
  scripts/transactions_exporter.py
  services/dashboard/docker-compose.yml
  yearn/constants.py
  yearn/db/models.py
  yearn/decorators.py
  yearn/middleware/middleware.py
  yearn/multicall2.py
  yearn/networks.py
  yearn/outputs/victoria/output_base.py
  yearn/prices/chainlink.py
  yearn/prices/constants.py
  yearn/prices/curve.py
  yearn/prices/uniswap/v2.py
  yearn/prices/yearn.py
  yearn/treasury/buckets.py
  yearn/treasury/treasury.py
  yearn/utils.py
  yearn/v2/registry.py
  yearn/yearn.py
Labels: enhancement, network

#298 [EXP-98-298] fix(test): more specific checkout ref
  .github/workflows/tests.partners.on_pull_req.yaml
  .github/workflows/tests.partners.on_push.yaml
Labels: safe to test

#296 [EXP-96-296] Added new Abra cauldrons
  scripts/abracadabra_wrappers.py
  yearn/partners/partners.py
  yearn/partners/snapshot.py
Labels: b2b, safe to test

#295 [EXP-95-295] GH Actions Testing Workflows
  .github/workflows/tests._fullsuite.yaml
  .github/workflows/tests.prices.aave.yaml
  .github/workflows/tests.prices.chainlink.yaml
  .github/workflows/tests.prices.compound.yaml
  .github/workflows/tests.prices.curve.yaml
  .github/workflows/tests.prices.fixed_forex.yaml
  .github/workflows/tests.prices.synthetix.yaml
  .github/workflows/tests.prices.uniswap.yaml
  .github/workflows/tests.yearn.iearn.yaml
  .github/workflows/tests.yearn.ironbank.yaml
  .github/workflows/tests.yearn.v1.yaml
  .github/workflows/tests.yearn.v2.yaml
  tests/apy/test_apy.py
  tests/conftest.py
  tests/fixtures/__init__.py
  tests/fixtures/decorators.py
  tests/partners/test_wrappers.py
  tests/prices/test_aave.py
  tests/prices/test_chainlink.py
  tests/prices/test_compound.py
  tests/prices/test_curve.py
  tests/prices/test_fixed_forex.py
  tests/prices/test_synthetix.py
  tests/prices/test_uniswap.py
  tests/v1/test_vault.py
  tests/yearn/__init__.py
  tests/yearn/test_iearn.py
  tests/yearn/test_ironbank.py
  tests/yearn/v1/__init__.py
  tests/yearn/v1/test_vault_v1.py
  tests/yearn/v2/__init__.py
  tests/yearn/v2/test_vault_v2.py
  yearn/iearn.py
  yearn/prices/chainlink.py
  yearn/prices/compound.py
  yearn/prices/curve.py
  yearn/v1/registry.py
  yearn/v2/vaults.py
Labels: do not merge
