Repository yearn/yearn-exporter, pull requests merged in 2022-05, with the labels that each got.

#301 [EXP-101-301] Add CoFi to partner
  yearn/partners/partners.py
Labels: b2b, safe to test

#311 [EXP-111-311] chore: bump eth_retry version
  .github/workflows/tests._fullsuite.yaml
  .github/workflows/tests.partners.on_pull_req.yaml
  .github/workflows/tests.partners.on_push.yaml
  requirements.txt
Labels: safe to test

#315 [EXP-115-315] Dashboard updates
  grafana/provisioning/dashboards/strategists/Ape.Tax Vault Overview.json
  grafana/provisioning/dashboards/strategists/Vault Management.json
  grafana/provisioning/dashboards/strategists/Vault Overview.json
  grafana/provisioning/dashboards/strategists/veCRV.json
  grafana/provisioning/dashboards/system/Are the Exporters Working.json
  grafana/provisioning/dashboards/system/Exporter Durations.json
Labels: enhancement

#306 [EXP-106-306] Element Partner Vaults
  yearn/partners/partners.py
  yearn/partners/snapshot.py
Labels: safe to test

#339 [EXP-139-339] chore: update badger treasury address
  yearn/partners/partners.py
Labels: safe to test
